### ISSUE TITLE
Problem with struct predeclaration and refId

### ISSUE THREAD

**Issue by counc009** [melt-umn/ableC#179]
I've run into a problem that ableC doesn't seem to connect struct pre-declarations with the eventual declaration that provides fields, specifically it seems to be related to refId. I'm guessing that the problem is that the pre-declaration lacks the refId attribute because ableC gives a syntax error for a pre-declaration with attributes (the following generates a parser error)
`struct __attribute__((refId("testing:struct:a"))) sa;`
while GCC does not produce an error.

An example that shows this error in practice
```
struct sa;

struct __attribute__((refId("testing:struct:b"))) sb {
  struct sa* ptr;
};

struct __attribute__((refId("testing:struct:a"))) sa {
  struct sb* ptr;
};

int main() {
  struct sa st_test;
  st_test.ptr = (void*) 0;
  return 0;
}
```
This gives me two errors one about the unknown storage size of struct sa and that it doesn't have defined fields. This code does compile in GCC. These errors disappear if the attributes are removed from the definition of struct sa.

**Comment by krame505** [comment]
Attributes on type expressions/typedefs need to come before the type, rather than after the struct keyword as in struct declarations - e.g. I think that
```
__attribute__((refId("testing:struct:a"))) struct sa;
```
should do what you want.

**Comment by counc009** [comment]
Thanks, that does seem to fix the problem I was having.
