### ISSUE TITLE
ADT extension requires manual recursive freeing

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC#2]
For all recursive ADTs, it is necessary to write a tedious and standard recursive freeing function.  This seems like code that could be generated.  

Alternatively, and even better, this could be implemented to use the [Boehm-Demers-Weiser garbage collector] (http://www.hboehm.info/gc/), so deallocation would be automatic.  I have been thinking of doing this as a separate extension that could get used by other extensions, as the library has a bunch of macro calls.  

Using garbage collection would probably be the best option, as I plan to build off this extension to add rewriting, etc. and manual freeing would get rather complex and hard to manage.

**Comment by tedinski** [comment]
I agree in many cases. I'm not entirely sure how to do this via an extension however. It seems like a difficult problem.

In the meantime, though, I think the ADT extension could generate deletion functions automatically just fine.

**Comment by krame505** [comment]
Adding a garbage collection extension should be easy.  The Boehm gc library just gives macro calls to replace malloc and realloc which are automatically freed.  Adding this as an extension would simply require expressions that would translate to the expansions of these macros, and possibly adding gcmalloc and gcrealloc keywords, or possibly other syntactic sugar for creating structs.  All the hard work is already done, and these expressions would be drop-in replacements for any malloc calls in the extension.
