### ISSUE TITLE
Remove "injectable" operator productions

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC#209]
Currently there exists a layer of forwarding "injectable" operator productions between type-based operator overloading and the host productions.  This mechanism poses issues for extensibility, and complicates tree sharing in operator overloading; this should be removed before starting on #207.  In the future this could be revisited, as some sort of rewriting pass.

**Comment by ericvanwyk** [comment]
Removing this is a fine thing. It should be reconsidered at some point though. There is currently no way to indicate that the injected code should not "muck up" the semantics of the code it is injected into. Perhaps Dawn's modular metatheory work will lead to a way to state, if not prove, what these kinds of extensions should be allowed (or not allowed) to do.
