### ISSUE TITLE
Get rid of parenType, parenTypeExpr

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC#43]
These productions are used to preserve parentheses written as part of a type expression, and don't have any semantic meaning.  As far as I can tell, parens are only needed in type expressions for function pointers?  Is there a reason we can't just add these parens when needed while pretty-printing the type expression, getting rid of these productions?  This was a point of confusion for me in trying to get function pointers working.

**Comment by ericvanwyk** [comment]
I think these should be removed.  Ted, any compelling reason they are there
now?

**Comment by tedinski** [comment]
Including things like this was one of the major innovations that made clang a better compiler than all the others when it comes to error messages. It reports back the type the user wrote, including how they parenthesized it, so it's comprehensible.

How is it getting in the way? The point of non-canonical type is that you should be able to ignore them.

**Comment by krame505** [comment]
Hmm, I suppose for error messages it would make sense.  The point of
confusion for me is that functionType must always be wrapped in parenType
when writing a function pointer, pointerType(functionType(...)) generates
syntactically invalid C code.

Lucas Kramer

**Comment by tedinski** [comment]
Ah, that's a bug to fix in the pretty printer, then.

**Comment by krame505** [comment]
Actually, it looks like I already fixed that bug as well.
