### ISSUE TITLE
Jenkins fails to mkdir first time

### ISSUE THREAD

**Issue by TravisCarlson** [melt-umn/ableC#57]
The feature/jenkins and fix/mwda-special-specifiers branches of ableC failed to build today. The logs showed the generated/ directory did not exist even after running `sh "mkdir -p generated"`. But the builds succeeded after simply running a second time.

**Comment by tedinski** [comment]
Did your change to use `dir` fix this, or have you not yet tested it?

**Comment by TravisCarlson** [comment]
Tested it and it didn't work. I reverted the use of dir in the type_qualifiers branch, which will hopefully be ready to merge before too long. This is still a problem.
