### ISSUE TITLE
Missing checks for L-values in assignment

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC#7]
AbleC currently allows assignment to non L-values.  As a very simple example, it allows code such as
`1 = 2;`
which is obviously not valid C.  
The solution to this would involve adding a new attribute to expressions
`synthesized attribute isLValue::Boolean occurs on Expr;`
to test if something is an L-value.  This would then be checked in assignments and an error would be raised if the left hand side is not an L-value.

**Comment by 200sc** [comment]
I'm starting to work on this, unless there's a reason it shouldn't be worked on.
