### ISSUE TITLE
Use sv-nailgun for expected-results tests

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC#72]
I'm not sure why, but we seem to just be re-invoking the jar for each test, which is considerably slower.  Since this is the script that gets run by Jenkins, is there any reason why this is not using sv-nailgun?

**Comment by TravisCarlson** [comment]
When I originally created the Jenkinsfile / expected-results scripts, I found the use of sv-nailgun was unreliable. Sometimes tests failed that normally passed with an error message indicating the test C file did not exist.

I tried running the tests using sv-nailgun a few times just now but couldn't reproduce it, everything seemed fine. I can try updating Jenkins and see if it's also reliable now, and if not update this issue with more details.

**Comment by krame505** [comment]
There are a few tests that were causing a crash or hanging for long periods of time, causing similar problems for me locally.  I since have disabled those tests in this branch, and it works fine on my machine.  I already have been messing around with using sv-nailgun for this locally, so I'll try pushing that in its own branch in a bit.
