### ISSUE TITLE
Move source grammar to a `grammars` directory

### ISSUE THREAD

**Issue by krame505** [melt-umn/ableC#98]
This would make things consistent with just about every other major Silver project, AFAIK.  Changing this will be annoying and break things, but waiting will make the problem worse... 

Also, I soon will want to be introducing a new grammar for the silver-ableC extension, which probably belongs under `edu.umn.cs.melt.exts.silver.ableC` and not part of the host language grammars - it would be good not to have these both sitting at the top level of the repo.  IDK, maybe the `builtins` processor grammar could move there, too.  

This is something I want to fix soon-ish, before diving into the implementation of the silver-ableC extension... so, thoughts?

**Comment by tedinski** [comment]
As conventions go, I'm ok with '.', 'src', and 'grammars' as the places to
put Silver grammars. I think AbleC is okay as is, but if you prefer a
different choice, your call.

**Comment by krame505** [comment]
It's just that both Silver and all the extensions have a `grammars` folder, so this might be a tad confusing otherwise... I certainly forget sometimes and try to `cd` into a non-existent `grammars` directory :-P

Also a related question, if we have both the grammars `edu.umn.cs.melt.ableC` and `edu.umn.cs.melt.exts.silver.ableC`, would Silver recognize them if they were seperate directories in the same `grammars` folder, or would they need to be under a directory named `edu.umn.cs.melt` for this to work?  I would prefer the former, to allow easier independent softlinking, but I'm not sure if Silver would recognize this structure?

**Comment by ericvanwyk** [comment]
I don't mind moving ``edu....ableC`` to a ``grammars`` directory.  @TravisCarlson  - any opinion?

As to your related question, I believe Silver will do what you want, but give it a try to verify.

**Comment by TravisCarlson** [comment]
I prefer `grammars`, since it's what so many other projects use, and because I'd prefer not to have more than one `edu...ableC` grammar directory at the top level.

**Comment by ericvanwyk** [comment]
OK, Lucas.  Go ahead and move it if you like.
